dh_doctrine_audit:
    timezone: 'America/Havana'
    table_prefix: ''
    table_suffix: '_audit'
    entities:
        App\Entity\Personal: ~
        App\Entity\Sexo: ~
        App\Entity\Pais: ~
        App\Entity\Provincia: ~
        App\Entity\Municipio: ~
        App\Entity\AreaSalud: ~
        App\Entity\CategoriaPaciente: ~
        App\Entity\CategoriaViajero: ~
        App\Entity\ConsejoPopular: ~
        App\Entity\EstadoIngreso: ~
        App\Entity\HospitalIngreso: ~
        App\Entity\Nacionalidad: ~
        App\Entity\Resultado: ~
        App\Entity\SintomasIngreso: ~
        App\Entity\TipoMuestra: ~