vich_uploader:
  db_driver: orm
  mappings:
    user_images:
      uri_prefix: '%app.path.user_images%'
      upload_destination: '%kernel.root_dir%/../public/uploads/images/user'

    personal_images:
      uri_prefix: '%app.path.personal_images%'
      upload_destination: '%kernel.root_dir%/../public/uploads/images/personal'

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

      #namer: vich_uploader.namer_uniqid