easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: 'Usuario'
            list:
                title: "Listado de Usuarios"
                item_permission: ['ROLE_SUPER_ADMIN', 'ROLE_ADMIN']
                fields: [{ property: 'image', type: 'image', base_path: '%app.path.user_images%' }, { property: 'username', label: 'Nombre Usuario' }, { property: 'enabled', label: 'Activo' }, { property: 'email', label: 'Email' }, { property: 'roles', label: 'Roles' }]
                actions: ['-show']
                max_results: 10
            form:
                fields:
                - { property: 'imageFile', type: 'vich_image' }
                - { property: 'username', label: 'Usuario', type_options: { required: true } }
                - { property: 'email', label: 'Email', type_options: { required: true } }
                - { property: 'enabled', label: 'Activo' }
                #- { property: 'lastLogin', label: 'Login' }
                - { property: 'plainPassword', label: 'Password', type_options: { required: false } }
                - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_DOCTOR': 'ROLE_DOCTOR', 'ROLE_ESTADISTICO': 'ROLE_ESTADISTICO', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }