# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'
    # Imagen del Usuario logueado
    app.path.user_images: /Sabio/public/uploads/images/user
    # Imagen del Personal
    app.path.personal_images: /Sabio/public/uploads/images/personal
    # Variables de las entidades - EasyAdmin
    permisos:
        ESCRITURA: ESCRITURA
        LECTURA: LECTURA
        CONTROL TOTAL: CONTROL TOTAL
    internet:
        SI: Si
        NO: No
    salidainternacional:
        SI: Si
        NO: No
    accesotelefonico:
        SI: Si
        NO: No
    serviciocorreo:
        SI: Si
        NO: No
    accesoredes:
        SI: S1
        NO: No
    mision:
        SI: Si
        NO: No
        NONE: None

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Twig,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.twig_extension:
        class: App\Twig\AppExtension
        public: true
        arguments:
           - '@doctrine.orm.entity_manager'
        tags:
           - { name: twig.extension }

    custom_service:
        class: App\Service\CustomService
        public: true

    app.controller.register:
        class: App\Controller\Bundle\FOSUserBundle\RegistrationController
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $formFactory: '@fos_user.registration.form.factory'
            $userManager: '@fos_user.user_manager'
            $tokenStorage: 'security.token_storage'
        calls:
        - method: setContainer
          arguments:
          - '@service_container'
        public: true

    FOS\UserBundle\Form\Factory\FactoryInterface:
        alias: 'fos_user.registration.form.factory'
        public: true