easy_admin:
    design:
      menu:
        - { label: 'HOME - USUARIO' }
        # Pagina Principal
        - { label: 'Home', url: 'http://127.0.0.1:8000/user/home', icon: 'home' }
        - label: 'Admin'
          icon: 'user'
          children:
          - { label: 'Listado Usuarios', icon: 'user', entity: 'User', permission: ['ROLE_SUPER_ADMIN', 'ROLE_ADMIN'] }